selhub:  
  image: selenium/hub:latest
  ports:
    - 4444:4444
  environment:
    - TZ=Europe/Berlin
    - GRID_BROWSER_TIMEOUT=480
    - GRID_TIMEOUT=240
    - GRID_DEBUG=false
    - GRID_CLEAN_UP_CYCLE=2000

firefox:  
  image: selenium/node-firefox-debug:latest
  links:
    - selhub:hub
  environment:
    - TZ=Europe/Berlin
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1080
  shm_size: 2g

chrome:  
  image: selenium/node-chrome-debug:latest
  links:
    - selhub:hub
  environment:
    - TZ=Europe/Berlin
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1080
  volumes:
    - /dev/shm:/dev/shm
